spring.application.name=Invoicehub
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Flow Force Quotation Branding Assets Configuration
flowforce.branding.logo=static/images/logo.png
flowforce.branding.signature=static/images/Umapathi-signature.png
